src/Entity/UserProgressTrack.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\ManyToOne;

#[Entity]
class UserProgressTrack
{

    #[Id, Column(type: 'integer'), GeneratedValue]
    private ?int $id;
    #[Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $createdAt;

    private function __construct(
        #[ManyToOne(inversedBy: 'progressTracks')]
        private UserProgress $progress,
        #[ManyToOne()]
        private QuestionWithAnswers $question,
        #[Column(type: 'json')]
        private array $userAnswers,
        #[Column(type: 'boolean')]
        private bool $isCorrect,

    ) {
        $this->createdAt = new \DateTimeImmutable();
    }

    public static function create(UserProgress $progress, QuestionWithAnswers $question, array $userAnswers, bool $isCorrect): UserProgressTrack
    {
        return new UserProgressTrack($progress, $question, $userAnswers, $isCorrect);
    }

    /**
     * @return string
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @return \DateTimeImmutable
     */
    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    /**
     * @return QuestionWithAnswers
     */
    public function getQuestion(): QuestionWithAnswers
    {
        return $this->question;
    }

    /**
     * @return string[]
     */
    public function getUserAnswers(): array
    {
        return $this->userAnswers;
    }

    /**
     * @return bool
     */
    public function isCorrect(): bool
    {
        return $this->isCorrect;
    }

    /**
     * @return UserProgress
     */
    public function getProgress(): UserProgress
    {
        return $this->progress;
    }


}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/questions.html.twig
{% extends "base.html.twig" %}
{% block body %}
    {% if myProgress.isFinished %}
        Test finished at {{ myProgress.finishedAt|date }}
        <table>
            <tr>
                <th>Question</th>
                <th>Answer</th>
                <th>Is Correct?</th>
            </tr>

            {% for progress in myProgress.progressTracks %}
                <tr>
                    <td>{{ progress.question.question }}</td>
                    <td>{{ progress.userAnswers|join("; ") }}</td>
                    <td style="color:{{ progress.correct ? 'green' : 'red' }}">{{ progress.correct ? 'YES' : 'NO' }}</td>
                </tr>
            {% endfor %}
            <form method="POST" action="{{ path('app_reset_progress') }}">
                <button type="submit">Reset progress</button>
            </form>

        </table>
    {% else %}
        <form method="POST" action="{{ path('app_answer', {'question': myProgress.upcomingQuestion.id}) }}">
            <label for={{ myProgress.upcomingQuestion.id }}>
                <div>{{ myProgress.upcomingQuestion.question }}</div>
                {% for option in myProgress.upcomingQuestion.answerOptions %}
                    <input name="answers[]" type="checkbox" value="{{ option }}"/>{{ option }}
                {% endfor %}
            </label>
            <hr/>
            <button type="submit">Answer and go next</button>
        </form>
        Questions to finish test: {{ myProgress.leftToFinish }}
    {% endif %}
{% endblock %}